### ISSUE TITLE
Options per workers

### ISSUE THREAD

**Issue by caevv** [oze4/workerpoolxt#13]
I know there are default options and per job options, but I want per worker options, is that possible? 

The reason is that I want to have an open connection to my RabbitMQ on a per workers basis, with the max set on `workerpoolxt.New()`, keep reusing that connection and not open a new one on every job.

**Comment by oze4** [comment]
Just as a disclaimer - **I hope you are not using this package in production!** [See here for more info on why you shouldn't use this package in production (***using github.com/gammazero/workerpool in production is fine, though***).

The only thing a worker does is run a func you gave to it - it has no concept of options. It just does the heavy lifting.

I could be misunderstanding, though.
