### ISSUE TITLE
Use multiple task & race conditions

### ISSUE THREAD

**Issue by BredSt** [oze4/workerpoolxt#3]
Hello!

We want to use the worker pool library and we found that this repository have some nice abstraction over it
and also the **timeout**  feature for each task which is definitely required. 

some questions.

1. in case of a timeout is there any event/way to know that task X exceed the timeout?  
example, some message like" "task 1 terminated as it exceed defined timeout"

2 . one thing that we are afraid is race condition for concurrent task , I know that the worker pool handle it and run tests to check it. does this library doing that also?   

Best Regards,
Bred

**Comment by oze4** [comment]
Hello! 

1. In order to check for errors on jobs, you can check the `Error` field on the `Response` object, something like this:

2. I believe this is a valid concern. I do not believe this is in issue with this library due to the fact we just wrap around workerpool.  The only concern I have as far as race conditions go would be using the experimental `WaitXTExperimental` method.

I am also working on getting tests implemented, to make sure there are no race conditions. So far, I have just been testing by hand.

### Examples

1. Check for errors

```golang
package main

import (
	"fmt"
	"time"

	"github.com/oze4/workerpoolxt"
)

func main() {
	wp := workerpoolxt.New(3, time.Duration(time.Second*10))

	wp.SubmitXT(workerpoolxt.Job{ // Uses default timeout
		Name: "Job 1 will pass",
		Task: func() workerpoolxt.Response {
			return workerpoolxt.Response{Data: "yay"}
		},
	})

	wp.SubmitXT(workerpoolxt.Job{ // Uses custom timeout
		Name:    "Job 2 will fail",
		Timeout: time.Duration(time.Millisecond * 1),
		Task: func() workerpoolxt.Response {
			time.Sleep(time.Second * 20) // Simulate long running task
			return workerpoolxt.Response{Data: "uhoh"}
		},
	})

	wp.SubmitXT(workerpoolxt.Job{ // Or if you encounter an error within the code in your job
		Name: "Job 3 will fail",
		Task: func() workerpoolxt.Response {
			err := fmt.Errorf("ErrorPretendException : something failed")
			if err != nil {
				return workerpoolxt.Response{Error: err}
			}
			return workerpoolxt.Response{Data: "uhoh"}
		},
	})

	results := wp.StopWaitXT()

	for _, r := range results {
		if r.Error != nil {
			fmt.Println(r.Name(), "has failed with error :", r.Error.Error())
		} else {
			fmt.Println(r.Name(), "has passed successfully")
		}
	}
}
```

2. `WaitXT` method

https://github.com/oze4/workerpoolxt/blob/dcc381377b1dded1b80695d3bad2dda91adeb5bf/workerpoolxt.go#L61-L80

**Comment by oze4** [comment]
@BredSt I finalized my [CI pipeline](https://github.com/oze4/workerpoolxt/actions) + added some tests & [code coverage](https://codecov.io/gh/oze4/workerpoolxt) today.  I also moved that experimental method to a [new branch](https://github.com/oze4/workerpoolxt/tree/experimental).

As far as race conditions - as far as I can tell, we do not have to worry about them within this library.  We offload the heavy lifting to `workerpool` and allow it to track jobs/active workers/etc.. 

All we do is wrap around the `func()` that is passed to `workerpool.StopWait()` and gather the results on a separate channel.

https://github.com/oze4/workerpoolxt/blob/a7cc1795b91fd16ee018a34f39e0e6bb020f25da/workerpoolxt.go#L36-L40

We also wrap around `workerpool.StopWait()`, so no real magic in this library.

https://github.com/oze4/workerpoolxt/blob/a7cc1795b91fd16ee018a34f39e0e6bb020f25da/workerpoolxt.go#L49-L59

**Comment by oze4** [comment]
Hey @BredSt I went ahead and added some tests specifically for race conditions. Again, we offload all of this to workerpool (we just embed WorkerPool) so I do not think we have to worry about race conditions at this level.  I took the race condition tests directly from workerpool, but I still think there are some niche tests that need to be written. I plan on doing that ASAP.

Please let me know if you have any questions.

**Comment by BredSt** [comment]
@oze4  - Hello again.

superb!

I went ahead and run the test several of times and the coverage is impressive
One test is not stable,  after couple of runs it fails ...

```
=== RUN   TestStopRace
    workerpoolxt_test.go:61: Stop should not return in any goroutine 
```

is it something that you working on ?

**Comment by oze4** [comment]
@BredSt nice find. I have not come across that yet. Thank you very much for testing this!

I am about to push some minor changes that may help with this. That test was taken directly from workerpool so I also need to dig more into what it does. I literally just copy and pasted it.

**Comment by BredSt** [comment]
Thank you very much for the hard work!

**Comment by oze4** [comment]
It looks like `workerpool` is the source of this error, [their test also appear to be failing](https://travis-ci.com/github/gammazero/workerpool/jobs/397675028).. I know `Pause(...)` is a new method that he (the person @ `workerpool`) just added last night. I'm sure he is aware of the issue, but I will file an issue over there.

**Comment by oze4** [comment]
@BredSt this def is 100% related to `workerpool v1.1.0` adding the `Pause(..)` method.  Which appears to be a new feature, which explains the kinks.

I have reverted to v1.0.0 and removed tests that call `Pause(..)` - tests appear to be fine now.

**Comment by BredSt** [comment]
@oze4  - I went a head and run some additional test, and there is serious issue.

I try to demo with simple example, run the following code as-is and hit the browser twice , 
the **first** hit is ok, you were able to get the results
the **second hit** (and more)  you will get a panic

run 
http://localhost:3000/test

code
```

package main

import (
	`fmt`
	`net/http`
	`time`

	wpxt "github.com/oze4/workerpoolxt"
)

func main() {

	wp := wpxt.New(3, time.Duration(time.Second*10))

	http.HandleFunc("/test", func(w http.ResponseWriter, r *http.Request) {

		// Uses default timeout
		wp.SubmitXT(wpxt.Job{
			Name: "Job 1 will pass",
			Task: func(o wpxt.Options) wpxt.Response {
				return wpxt.Response{Data: "yay"}
			},
		})

		// Uses custom timeout
		// This job is configured to timeout on purpose
		wp.SubmitXT(wpxt.Job{
			Name:    "Job 2 will timeout",
			Timeout: time.Duration(time.Millisecond * 1),
			Task: func(o wpxt.Options) wpxt.Response {
				// Simulate long running task
				time.Sleep(time.Second * 20)
				return wpxt.Response{Data: "timedout"}
			},
		})

		// Or if you encounter an error within the code in your job
		wp.SubmitXT(wpxt.Job{
			Name: "Job 3 will encounter an error",
			Task: func(o wpxt.Options) wpxt.Response {
				err := fmt.Errorf("ErrorPretendException : something failed")
				if err != nil {
					return wpxt.Response{Error: err}
				}
				return wpxt.Response{Data: "error"}
			},
		})

		results := wp.StopWaitXT()

		for _, r := range results {
			if r.Error != nil {
				fmt.Println(r.Name(), "has failed with error :", r.Error.Error())
			} else {
				fmt.Println(r.Name(), "has passed successfully")
			}
		}
	})


	fmt.Println("running")
	e := http.ListenAndServe(":3000", nil)
	if e != nil {
		fmt.Println(e)
	}
}

```

**Comment by oze4** [comment]
It looks like that is happening because you create a new workerpool outside of the handler. That's why it works the first time but not the second because it's trying to use the same workerpool which has already been stopped. 

This should fix it. 

```golang
// ...
http.HandleFunc("/test", func(w http.ResponseWriter, r *http.Request) {
    // Move creation of wp into the handler 
    wp := wpxt.New(3, time.Duration(time.Second*10))
    // ...
}
```

**Comment by BredSt** [comment]
Thanks my fault

**Comment by oze4** [comment]
@BredSt no worries, it happens - I'd be lying if I said I haven't overlooked such things 😆
