### ISSUE TITLE
Suggestion for retry

### ISSUE THREAD

**Issue by DavidMet** [oze4/workerpoolxt#6]
HI,

It looks for me very nice and will try to use it, great work!
One feature which could be a very neat is to run the workers with **retry** mechanism ,
e.g. as I define a timeout for a job, in case the job run and get an error run some retry (until the timeout reached)
WDYT?

Regards,
David

**Comment by oze4** [comment]
I'm def open to the idea.. Are you referring to a retry func or a retry int that represents N retries?

Part of me feels like this is something that could be implemented I'm user land as is. If you get a job with an error, just retry it. Or inside the job code the logic to retry on failure. 

While that may be a nice feature, I'm torn on whether or not retrying jobs is the responsibility of this library or not.

Thoughts?

**Comment by BredSt** [comment]
Yes, user can use his retry or backoff, but this feature doesn't exist on worker-pool lib and adding it to your library could be a neat feature.

**Comment by oze4** [comment]
I'll get something spun up to see what you all think. Hopefully by tomorrow - if you have any ideas on implementation, I'd be happy to accept PRs!

I do like the idea of neat but I also embrace the Go philosophy of keeping things simple. 

For example, the job timeouts, the job options, and capturing job return are things that "couldn't" be implemented in user land. Retrying jobs on the other hand could be implemented in user land. 

So when is it a feature and when is it just meeting a specific, even niche, use case? Is it a feature of it could be implemented in user land with less overhead? I think so. 

Perhaps we should focus on some way to make things modular? If you want to use the retry "module" you can, etc... This would also mean "modularising" job timeouts as well. I think supplying options and capturing return should be base functionality and everything else modular..

Thoughts?

**Comment by DavidMet** [comment]
Mine two cents, is to baked in something like 

https://pkg.go.dev/github.com/cenkalti/backoff/v4#pkg-overview , WDYT?

**Comment by oze4** [comment]
I like it! Looks like a great way to implement this

**Comment by oze4** [comment]
@DavidMet @BredSt something like this? It looks like a test is failing now, which I will have to look into later (along with cleaning up the code).  I just wanted to get something on "paper"..

https://github.com/oze4/workerpoolxt/blob/f3dede37c040648bdd1c06a4bdaa496d30277445/workerpoolxt.go#L81-L142

Line 172:

https://github.com/oze4/workerpoolxt/blob/f3dede37c040648bdd1c06a4bdaa496d30277445/workerpoolxt.go#L166-L173

**Comment by oze4** [comment]
@DavidMet @BredSt fixed the issue with the failing test.. Outside of optimizing the code, everything *should* be working...

**Comment by oze4** [comment]
Implemented in https://github.com/oze4/workerpoolxt/releases/tag/v1.0.3

**Comment by DavidMet** [comment]
Superb! awesome work

Will check it, could you please just explain how it will work with the timeout that you have provided per the jobs, does it have a sync with the retry timeout ?
